spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bookinn_app}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: bookinn_schema
      connection-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: "create"
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

logging:
  level:
    root: INFO
