version: "3.9"
services:

  postgres:
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookinn_app
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
